---
abstract: 'Sending files over a socket efficiently and cross-platform'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  IO::Socket::INET: 0
  Module::Build: 0.3601
  Socket: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Send
requires:
  Carp: 0
  Errno: 0
  Fcntl: 0
  Sub::Exporter::Progressive: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=File-Send
  repository: git://github.com/Leont/file-send.git
version: 0.002
